/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogs;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import services.DatabaseConnection;
import utilities.ToastMessage;
import views.Notes;

/**
 *
 * @author 2ndyrGroupB
 */
public class Access extends javax.swing.JDialog {
DatabaseConnection db=new DatabaseConnection();
    /**
     * Creates new form Access
     */
    public Access(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setField();
        getData();
    }

    private void setField(){
        message.setText(new Notes().requestMessage);
        String set=new Notes().sharedUser.substring(0, 1).toUpperCase() + new Notes().sharedUser.substring(1);
        request.setText(set+" request to edit your note");
    }
    public Access() {
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Access dialog = new Access(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        request = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        aprrove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteContent = new javax.swing.JTextArea();
        noteTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        request.setForeground(new java.awt.Color(255, 255, 255));
        request.setText("Request Access to edit");
        jPanel1.add(request, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, 230, -1));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("x");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 20, 20));

        jButton1.setBackground(new java.awt.Color(255, 51, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancel");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 50, 20));

        message.setForeground(new java.awt.Color(255, 255, 255));
        message.setText("jLabel3");
        message.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        message.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 60));

        aprrove.setBackground(new java.awt.Color(255, 255, 255));
        aprrove.setText("Approve");
        aprrove.setBorder(null);
        aprrove.setContentAreaFilled(false);
        aprrove.setOpaque(true);
        aprrove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aprroveMouseClicked(evt);
            }
        });
        aprrove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprroveActionPerformed(evt);
            }
        });
        jPanel1.add(aprrove, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 50, 20));

        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        noteContent.setEditable(false);
        noteContent.setBackground(new java.awt.Color(51, 51, 255));
        noteContent.setColumns(20);
        noteContent.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        noteContent.setForeground(new java.awt.Color(255, 255, 255));
        noteContent.setLineWrap(true);
        noteContent.setRows(5);
        noteContent.setWrapStyleWord(true);
        noteContent.setBorder(null);
        jScrollPane1.setViewportView(noteContent);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, 170));

        noteTitle.setForeground(new java.awt.Color(255, 255, 255));
        noteTitle.setText("jLabel3");
        jPanel1.add(noteTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Owner: You");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 110, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void aprroveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprroveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aprroveActionPerformed

    private void aprroveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aprroveMouseClicked
        String qry = "update shared set status='1' where noteID='"+new Notes().viewID+"' and sharesTo='"+new Notes().sharedUser+"'";
        String delete = "delete from shared where noteID='" + new Notes().viewID + "' and requestby='"+new Notes().sharedUser+"'";
        int status=0;
        try {
            status=db.getStatement().executeUpdate(qry);
            status=db.getStatement().executeUpdate(delete);
        } catch (SQLException ex) {
            System.err.println(ex);
        } catch (Exception ex) {
            System.err.println(ex);
        } finally {
            if (db.getConnection() != null) {
                try {
                    db.closeConnection();
                } catch (Exception ex) {
                    Logger.getLogger(Access.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if(status==1){
            new ToastMessage(this.getRootPane(), "Approve Successfully","success");
            new Notes().dispose();
            new Notes().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_aprroveMouseClicked

    private void getData(){
         String sql = "SELECT * from notes WHERE noteID='" + new Notes().viewID + "'";
        try {

            ResultSet rs = db.Query(sql);
            while (rs.next()) {
              noteTitle.setText("Title: "+rs.getString(3));
              noteContent.setText("Content:\n"+rs.getString(4));
            }
          
        } catch (Exception ex) {
            System.out.println(ex);
            ex.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Access dialog = new Access(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aprrove;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel message;
    private javax.swing.JTextArea noteContent;
    private javax.swing.JLabel noteTitle;
    private javax.swing.JLabel request;
    // End of variables declaration//GEN-END:variables
}
