/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.card;

import java.awt.Component;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import models.NotificationMessage;
//import models.NoteObject;

/**
 *
 * @author 2ndyrGroupB
 */
public class NotificationMessageCard extends javax.swing.JPanel implements ListCellRenderer<NotificationMessage>  {

    /**
     * Creates new form NotificationMessagecard
     */
    public NotificationMessageCard() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        name.setForeground(new java.awt.Color(51, 51, 51));
        name.setText("jLabel1");
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 190, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 3, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dist/images/info-5-24.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 14, -1, 40));

        content.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        content.setForeground(new java.awt.Color(102, 102, 102));
        content.setText("jLabel3");
        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 34, 190, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dist/images/message_drop.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 70));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends NotificationMessage> list, NotificationMessage value, int index, boolean isSelected, boolean cellHasFocus) {
       name.setText(value.getName());
       content.setText(value.getMessage());
       return this;
    }
}
