/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.index;

import views.Signup;
import java.awt.Color;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.geom.RoundRectangle2D;
import java.awt.Shape;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import utilities.MyFont;

/**
 *
 * @author 2ndyrGroupB
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
      configureFont();
    }

     private void configureFont(){
        new MyFont(brand, 20,"medium");
        new MyFont(freeNote, 16,"medium");
        new MyFont(getStartedBtn, 13);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        startContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        freeNote = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        getStartedBtn = new javax.swing.JButton();
        close = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame"); // NOI18N
        setUndecorated(true);

        startContainer.setBackground(new java.awt.Color(255, 255, 255));
        startContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        startContainer.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                startContainerMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                startContainerMouseMoved(evt);
            }
        });
        startContainer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                startContainerMousePressed(evt);
            }
        });
        startContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/get_started.png"))); // NOI18N
        startContainer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 290, 240));

        freeNote.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        freeNote.setForeground(new java.awt.Color(51, 51, 51));
        freeNote.setText("Create Free Notes ");
        startContainer.add(freeNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        brand.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        brand.setForeground(new java.awt.Color(51, 51, 255));
        brand.setText("MiNote");
        startContainer.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("<html>A simple and fast way to keep important ideas in one place</html>");
        startContainer.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 221, 35));

        getStartedBtn.setBackground(new java.awt.Color(51, 51, 255));
        getStartedBtn.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        getStartedBtn.setForeground(new java.awt.Color(255, 255, 255));
        getStartedBtn.setText("Get Started");
        getStartedBtn.setBorder(null);
        getStartedBtn.setContentAreaFilled(false);
        getStartedBtn.setFocusPainted(false);
        getStartedBtn.setOpaque(true);
        getStartedBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getStartedBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                getStartedBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                getStartedBtnMouseExited(evt);
            }
        });
        startContainer.add(getStartedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 101, 39));

        close.setBackground(new java.awt.Color(51, 51, 255));
        close.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("x");
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        startContainer.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(startContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void getStartedBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getStartedBtnMouseEntered
        // TODO add your handling code here:
        this.getStartedBtn.setBackground(new Color(31, 31, 209));
    }//GEN-LAST:event_getStartedBtnMouseEntered

    private void getStartedBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getStartedBtnMouseClicked
        // TODO add your handling code here:
        new Signup().setVisible(true);
        this.dispose();
//        6666FF
    }//GEN-LAST:event_getStartedBtnMouseClicked
private static int tx, ty;

    private void getStartedBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getStartedBtnMouseExited
        // TODO add your handling code here:
         this.getStartedBtn.setBackground(new Color(51,51,255));
    }//GEN-LAST:event_getStartedBtnMouseExited

    private void startContainerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startContainerMouseDragged
        // TODO add your handling code here:
//        this.setLocation(evt.getXOnScreen() -tx, evt.getYOnScreen() -ty);
    }//GEN-LAST:event_startContainerMouseDragged

    private void startContainerMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startContainerMouseMoved
        // TODO add your handling code here:
//       startContainer.setLocation(evt.getXOnScreen() -tx, evt.getYOnScreen() -ty);
    }//GEN-LAST:event_startContainerMouseMoved

    private void startContainerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startContainerMousePressed
        // TODO add your handling code here:
//         tx= evt.getX();
//    ty=evt.getY();
    }//GEN-LAST:event_startContainerMousePressed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        this.close.setBackground(Color.red);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        this.close.setBackground(new Color(51,51,255));
    }//GEN-LAST:event_closeMouseExited
 public void hoverEffect(JLabel hover,Color rand){
        hover.setBackground(rand);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brand;
    private javax.swing.JLabel close;
    private javax.swing.JLabel freeNote;
    private javax.swing.JButton getStartedBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel startContainer;
    // End of variables declaration//GEN-END:variables
}
