/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.NoteController;
import views.auth.Login;
import java.awt.Color;
import java.awt.KeyboardFocusManager;
import java.awt.geom.RoundRectangle2D;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilities.MyFont;
import utilities.ToastMessage;
import views.Notes;

/**
 *
 * @author 2ndyrGroupB
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Signup() {
        initComponents();
        KeyboardFocusManager.getCurrentKeyboardFocusManager().clearGlobalFocusOwner();
        getContentPane().requestFocusInWindow();
        password.setEchoChar((char) 0);
        configureFont();

    }

    private void configureFont() {
        new MyFont(signup, 20, "medium");
        new MyFont(email, 14);
        new MyFont(username, 14);
        new MyFont(password, 14);
        new MyFont(haveAccount, 11);
        new MyFont(register, 12);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        signupContainer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        emailForm = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        showHide = new javax.swing.JLabel();
        usernameForm = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        emailForm1 = new javax.swing.JPanel();
        email = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        haveAccount = new javax.swing.JLabel();
        loginNowBtn = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        signup = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signupContainer.setBackground(new java.awt.Color(255, 255, 255));
        signupContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        signupContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/register.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        signupContainer.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 295, 196));

        emailForm.setBackground(new java.awt.Color(255, 255, 255));
        emailForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        emailForm.setLayout(null);

        password.setForeground(new java.awt.Color(51, 51, 255));
        password.setText("Enter Password");
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        emailForm.add(password);
        password.setBounds(11, 12, 195, 18);

        showHide.setBackground(new java.awt.Color(51, 51, 255));
        showHide.setForeground(new java.awt.Color(255, 255, 255));
        showHide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dist/images/eye-off.png"))); // NOI18N
        showHide.setOpaque(true);
        showHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showHideMouseClicked(evt);
            }
        });
        emailForm.add(showHide);
        showHide.setBounds(220, 0, 40, 40);

        signupContainer.add(emailForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 260, 40));

        usernameForm.setBackground(new java.awt.Color(255, 255, 255));
        usernameForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        username.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(51, 51, 255));
        username.setText("Enter Username");
        username.setBorder(null);
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usernameFormLayout = new javax.swing.GroupLayout(usernameForm);
        usernameForm.setLayout(usernameFormLayout);
        usernameFormLayout.setHorizontalGroup(
            usernameFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usernameFormLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        usernameFormLayout.setVerticalGroup(
            usernameFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernameFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        signupContainer.add(usernameForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 260, 40));

        emailForm1.setBackground(new java.awt.Color(255, 255, 255));
        emailForm1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        email.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(51, 51, 255));
        email.setText("Enter Email");
        email.setBorder(null);
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout emailForm1Layout = new javax.swing.GroupLayout(emailForm1);
        emailForm1.setLayout(emailForm1Layout);
        emailForm1Layout.setHorizontalGroup(
            emailForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emailForm1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        emailForm1Layout.setVerticalGroup(
            emailForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailForm1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        signupContainer.add(emailForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, 40));

        register.setBackground(new java.awt.Color(51, 51, 255));
        register.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Proceed");
        register.setToolTipText("Register Now\n");
        register.setBorderPainted(false);
        register.setContentAreaFilled(false);
        register.setFocusPainted(false);
        register.setOpaque(true);
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerMouseExited(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        signupContainer.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 120, 40));

        haveAccount.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        haveAccount.setText("Already have an account?");
        signupContainer.add(haveAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        loginNowBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        loginNowBtn.setForeground(new java.awt.Color(0, 0, 255));
        loginNowBtn.setText("Log In Now");
        loginNowBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginNowBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginNowBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginNowBtnMouseExited(evt);
            }
        });
        signupContainer.add(loginNowBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setOpaque(false);

        close.setBackground(new java.awt.Color(51, 51, 255));
        close.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("x");
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });

        signup.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        signup.setForeground(new java.awt.Color(51, 51, 255));
        signup.setText("Sign Up");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(signup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(signup))
        );

        signupContainer.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 40));

        getContentPane().add(signupContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 321, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        // TODO add your handling code here:
        if (username.getText().equals("Enter Username")) {
            username.setText("");
        }
    }//GEN-LAST:event_usernameMouseClicked

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        if (username.getText().equals("")) {
            username.setText("Enter Username");
        }
    }//GEN-LAST:event_usernameFocusLost

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        if (email.getText().equals("")) {
            email.setText("Enter Email");
        }
    }//GEN-LAST:event_emailFocusLost

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
        if (email.getText().equals("Enter Email")) {
            email.setText("");
        }
    }//GEN-LAST:event_emailMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        // TODO add your handling code here:
        if (String.valueOf(password.getPassword()).equals("Enter Password")) {
            password.setText("");

        }
        password.setEchoChar('*');
    }//GEN-LAST:event_passwordMouseClicked

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        if (String.valueOf(password.getPassword()).equals("")) {
            password.setText("Enter Password");
            password.setEchoChar((char) 0);
        }
        if (!String.valueOf(password.getPassword()).equals("Enter Password")) {
            password.setEchoChar('*');
        }

    }//GEN-LAST:event_passwordFocusLost

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered
        // TODO add your handling code here:
        this.register.setBackground(new Color(31, 31, 209));
    }//GEN-LAST:event_registerMouseEntered

    private void registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseExited
        // TODO add your handling code here:
        this.register.setBackground(new Color(51, 51, 255));
    }//GEN-LAST:event_registerMouseExited

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained


    }//GEN-LAST:event_passwordFocusGained

    private void loginNowBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginNowBtnMouseEntered
        // TODO add your handling code here:
        this.loginNowBtn.setText("<html><u>Log In Now</u></html>");
    }//GEN-LAST:event_loginNowBtnMouseEntered

    private void loginNowBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginNowBtnMouseExited
        this.loginNowBtn.setText("<html>Log In Now</html>");
    }//GEN-LAST:event_loginNowBtnMouseExited

    private void loginNowBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginNowBtnMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginNowBtnMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        this.close.setBackground(Color.red);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        this.close.setBackground(new Color(51, 51, 255));
    }//GEN-LAST:event_closeMouseExited


    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        // TODO add your handling code here:
        NoteController controller = new NoteController();
        int result = 0;
        try {
            if (username.getText().equals("Enter Username") || email.getText().equals("Enter Email") || String.valueOf(password.getPassword()).equals("Enter Password")) {
                new ToastMessage(signupContainer, "All Fields are required", "error");
            } else {
                result = controller.registerUser(username, email, password);
            }

        } catch (Exception ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (result == 1) {
            new ToastMessage(signupContainer, "Created Successfully", "success");
            this.dispose();
            new Login().setVisible(true);
        } else {
            new ToastMessage(signupContainer, "Error", "error");
        }

    }//GEN-LAST:event_registerMouseClicked
 boolean showPass=false;
    private void showHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showHideMouseClicked
        // TODO add your handling code here:
       
        if (!showPass) {
            password.setEchoChar((char) 0);
            showHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dist/images/eye.png")));
            showPass = true;
        } else {
            password.setEchoChar('*');
            showHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dist/images/eye-off.png")));
            showPass = false;
        }
    }//GEN-LAST:event_showHideMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JTextField email;
    private javax.swing.JPanel emailForm;
    private javax.swing.JPanel emailForm1;
    private javax.swing.JLabel haveAccount;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel loginNowBtn;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton register;
    private javax.swing.JLabel showHide;
    private javax.swing.JLabel signup;
    private javax.swing.JPanel signupContainer;
    private javax.swing.JTextField username;
    private javax.swing.JPanel usernameForm;
    // End of variables declaration//GEN-END:variables
}
