/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.auth;

import controllers.AuthController;
import java.awt.Color;
import java.awt.KeyboardFocusManager;
import services.DatabaseConnection;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import utilities.MyFont;
import views.Signup;
import utilities.ToastMessage;
import models.User;
import views.Notes;

/**
 *
 * @author 2ndyrGroupB
 */
public class Login extends javax.swing.JFrame {

    public static int userID;
    public static String userName;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        KeyboardFocusManager.getCurrentKeyboardFocusManager().clearGlobalFocusOwner();
        getContentPane().requestFocusInWindow();
        passwordLogin.setEchoChar((char) 0);
        configureFont();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signupContainer = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        passwordFormLogin = new javax.swing.JPanel();
        showHide = new javax.swing.JLabel();
        passwordLogin = new javax.swing.JPasswordField();
        emailForm1 = new javax.swing.JPanel();
        emailLogin = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dontHave = new javax.swing.JLabel();
        registerBtn = new javax.swing.JLabel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        signupContainer.setBackground(new java.awt.Color(255, 255, 255));
        signupContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        signupContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        welcome.setForeground(new java.awt.Color(51, 51, 255));
        welcome.setText("Welcome Back");
        signupContainer.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        passwordFormLogin.setBackground(new java.awt.Color(255, 255, 255));
        passwordFormLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        passwordFormLogin.setLayout(null);

        showHide.setBackground(new java.awt.Color(51, 51, 255));
        showHide.setForeground(new java.awt.Color(255, 255, 255));
        showHide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dist/images/eye-off.png"))); // NOI18N
        showHide.setOpaque(true);
        showHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showHideMouseClicked(evt);
            }
        });
        passwordFormLogin.add(showHide);
        showHide.setBounds(220, 0, 40, 40);

        passwordLogin.setForeground(new java.awt.Color(51, 51, 255));
        passwordLogin.setText("Enter Password");
        passwordLogin.setBorder(null);
        passwordLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordLoginFocusLost(evt);
            }
        });
        passwordLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordLoginMouseClicked(evt);
            }
        });
        passwordLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordLoginKeyPressed(evt);
            }
        });
        passwordFormLogin.add(passwordLogin);
        passwordLogin.setBounds(20, 12, 190, 16);

        signupContainer.add(passwordFormLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 260, 40));

        emailForm1.setBackground(new java.awt.Color(255, 255, 255));
        emailForm1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        emailLogin.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        emailLogin.setForeground(new java.awt.Color(51, 51, 255));
        emailLogin.setText("Enter your Email");
        emailLogin.setBorder(null);
        emailLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailLoginFocusLost(evt);
            }
        });
        emailLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailLoginMouseClicked(evt);
            }
        });
        emailLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout emailForm1Layout = new javax.swing.GroupLayout(emailForm1);
        emailForm1.setLayout(emailForm1Layout);
        emailForm1Layout.setHorizontalGroup(
            emailForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emailForm1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(emailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        emailForm1Layout.setVerticalGroup(
            emailForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailForm1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(emailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        signupContainer.add(emailForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 260, 40));

        loginBtn.setBackground(new java.awt.Color(51, 51, 255));
        loginBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Proceed");
        loginBtn.setToolTipText("Register Now\n");
        loginBtn.setBorderPainted(false);
        loginBtn.setContentAreaFilled(false);
        loginBtn.setFocusPainted(false);
        loginBtn.setOpaque(true);
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        signupContainer.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 120, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/loginheader.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        signupContainer.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 280, 230));

        dontHave.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        dontHave.setText("Don't have an account?");
        signupContainer.add(dontHave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        registerBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(0, 0, 255));
        registerBtn.setText("Register Now");
        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerBtnMouseExited(evt);
            }
        });
        signupContainer.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        close.setBackground(new java.awt.Color(51, 51, 255));
        close.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("x");
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        signupContainer.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signupContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signupContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void configureFont() {
        new MyFont(welcome, 20, "medium");
        new MyFont(loginBtn, 12);
        new MyFont(emailLogin, 14);
        new MyFont(passwordLogin, 14);
        new MyFont(dontHave, 11);
    }
    private void passwordLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLoginFocusGained
        if (String.valueOf(passwordLogin.getPassword()).equals("Enter Password")) {
            passwordLogin.setText("");
        }
        passwordLogin.setEchoChar('*');
    }//GEN-LAST:event_passwordLoginFocusGained

    private void passwordLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLoginFocusLost

        if (String.valueOf(passwordLogin.getPassword()).equals("")) {
            passwordLogin.setText("Enter Password");
            passwordLogin.setEchoChar((char) 0);
        }
        if (!String.valueOf(passwordLogin.getPassword()).equals("Enter Password")) {
            passwordLogin.setEchoChar('*');
        }
    }//GEN-LAST:event_passwordLoginFocusLost

    private void passwordLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordLoginMouseClicked
        // TODO add your handling code here:
        if (String.valueOf(passwordLogin.getPassword()).equals("Enter Password")) {
            passwordLogin.setText("");

        }
        passwordLogin.setEchoChar('*');


    }//GEN-LAST:event_passwordLoginMouseClicked

    private void emailLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailLoginFocusLost
        // TODO add your handling code here:
        if (emailLogin.getText().equals("")) {
            emailLogin.setText("Enter your Email");
        }
    }//GEN-LAST:event_emailLoginFocusLost

    private void emailLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailLoginMouseClicked
        // TODO add your handling code here:
        if (emailLogin.getText().equals("Enter your Email")) {
            emailLogin.setText("");
        }
    }//GEN-LAST:event_emailLoginMouseClicked

    private void emailLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailLoginActionPerformed

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
        // TODO add your handling code here:
        this.loginBtn.setBackground(new Color(31, 31, 209));
    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        // TODO add your handling code here:
        this.loginBtn.setBackground(new Color(51, 51, 255));
    }//GEN-LAST:event_loginBtnMouseExited

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnActionPerformed

    private void registerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseEntered

        this.registerBtn.setText("<html><u>Register Now</u></html>");

    }//GEN-LAST:event_registerBtnMouseEntered

    private void registerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseExited
        this.registerBtn.setText("<html>Register Now</html>");
    }//GEN-LAST:event_registerBtnMouseExited

    private void registerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseClicked
        // TODO add your handling code here:
        new Signup().setVisible(true);
    }//GEN-LAST:event_registerBtnMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        this.close.setBackground(Color.red);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        this.close.setBackground(new Color(51, 51, 255));
    }//GEN-LAST:event_closeMouseExited


    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        submit();

    }//GEN-LAST:event_loginBtnMouseClicked

    private void submit() {
        String email = this.emailLogin.getText();
        String password = String.valueOf(this.passwordLogin.getPassword());

        DatabaseConnection db = new DatabaseConnection();
        User user=new User();
        user.setEmail(email);
        user.setPassword(password);
        new AuthController().login(user,db,this);
//        String sql = "Select * from users where email='" + email + "' and password='" + password + "'";
//        boolean loggedIn = false;
//        if (email.equals("Enter your Email") || password.equals("Enter Password")) {
//            new ToastMessage(signupContainer, "All Fields are required", "error");
//        } else {
//            try {
//                db.openConnection();
//                ResultSet rs = db.Query(sql);
//                while (rs.next()) {
//                    userID = rs.getInt("userID");
//                    userName = rs.getString("username");
//                    loggedIn = true;
//                }
//            } catch (Exception ex) {
//                System.err.print(ex);
//            }
//            if (loggedIn) {
//                new ToastMessage(signupContainer, greetUser() + " " + userName, "success");
//
//                new Notes().setVisible(true);
//                this.dispose();
//
//            } else {
//                new ToastMessage(signupContainer, "Invalid username or password", "error");
//
//            }
//        }
    }

    private String greetUser() {
        Calendar c = Calendar.getInstance();
        int hours = c.get(Calendar.HOUR_OF_DAY);
        String greeting = null;
        if (hours >= 1 && hours <= 12) {
            greeting = "Good Morning";
        } else if (hours >= 12 && hours <= 16) {
            greeting = "Good Afternoon";
        } else if (hours >= 16 && hours <= 21) {
            greeting = "Good Evening";
        } else if (hours >= 21 && hours <= 24) {
            greeting = "Good Night";
        }
        return greeting;
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void passwordLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordLoginKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            submit();
        }
    }//GEN-LAST:event_passwordLoginKeyPressed

    private void emailLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailLoginFocusGained
        if (emailLogin.getText().equals("Enter your Email")) {
            emailLogin.setText("");
        }
    }//GEN-LAST:event_emailLoginFocusGained
    boolean showPass = false;
    private void showHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showHideMouseClicked
        // TODO add your handling code here:
        if (!showPass) {
            passwordLogin.setEchoChar((char) 0);
            showHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dist/images/eye.png")));
            showPass = true;
        } else {
            passwordLogin.setEchoChar('*');
            showHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dist/images/eye-off.png")));
            showPass = false;
        }

    }//GEN-LAST:event_showHideMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel dontHave;
    private javax.swing.JPanel emailForm1;
    private javax.swing.JTextField emailLogin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel passwordFormLogin;
    private javax.swing.JPasswordField passwordLogin;
    private javax.swing.JLabel registerBtn;
    private javax.swing.JLabel showHide;
    private javax.swing.JPanel signupContainer;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
